### ISSUE TITLE
Build for UE 5.2 failed

### ISSUE THREAD

**Issue by afrostalin** [microsoft/ProjectAcoustics#173]
Hello there, after some fixes in plugin it's still can't be compiled. Error we got: 
```
>[131/329] Compile [x64] Module.ProjectAcousticsBakeUI.cpp
0>E:\Job\Project\Plugins\ProjectAcousticsNative\Intermediate\Build\Win64\x64\UnrealEditor\Development\ProjectAcousticsBakeUI\Module.ProjectAcousticsBakeUI.cpp: Error C1001 : Internal compiler error.
0>(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)

```
Are there any ways to get around this? This is a very serious problem for us when moving to a new unreal engine version.

**Comment by KyleStorck** [comment]
We do not offer support for UE 5.2 on the marketplace currently. No ETA on when we will offer that support. We'll keep you updated.

In the meantime, it sounds like you're making changes to the plugin to try to get it to compile? If so, here are some unofficial changes I made to the 5.1 plugin that should make it compile in UE 5.2.

![image](https://github.com/microsoft/ProjectAcoustics/assets/1233941/0a577170-bed5-40be-af6e-3894dfd6460a)
![image](https://github.com/microsoft/ProjectAcoustics/assets/1233941/95be358b-eacc-41a8-a58b-0d2959f0d315)

**Comment by afrostalin** [comment]
Hey, thanks for you reply. I did everything exactly the same, but my mistake was in using const TCHAR [] for error string, now compile success :)

Best regards
